version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: flight_system_container
    restart: always
    environment:
      POSTGRES_USER: {DB_USER}
      POSTGRES_PASSWORD: {DB_PASSWORD}
      POSTGRES_DB: {DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - flight_db_data:/var/lib/postgresql/data

volumes:
  flight_db_data: