
DROP TABLE IF EXISTS airline_members CASCADE;
DROP TABLE IF EXISTS booking CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS seats CASCADE;
DROP TABLE IF EXISTS flights CASCADE;
DROP TABLE IF EXISTS airplanes CASCADE;
DROP TABLE IF EXISTS airports CASCADE;
DROP TABLE IF EXISTS users CASCADE;


DROP EXTENSION IF EXISTS "uuid-ossp";

